"use client";
import svgPaths from "./logo-paths";

export default function Group() {
  return (
    <div className="relative size-full">
      <svg
        className="absolute inset-0 block size-full transition-colors duration-300"
        fill="none"
        preserveAspectRatio="none"
        viewBox="0 0 1840.38 1914.2"
      >
        <g clipPath="url(#clip0_33_1121)" id="Group 3">
          <path d={svgPaths.p2a257c00} fill="var(--logo-base)" id="Vector" />
          <path d={svgPaths.p2cedbf80} fill="var(--logo-primary)" id="Vector_2" />
          <path d={svgPaths.p3b3f24c0} fill="var(--logo-primary)" id="Vector_3" />
          <path d={svgPaths.p2d5cec00} fill="var(--logo-soft)" id="Vector_4" />
          <path d={svgPaths.p15634800} fill="var(--logo-soft)" id="Vector_5" />
          <path d={svgPaths.p3cceb1f0} fill="var(--logo-soft)" id="Vector_6" />
          <path d={svgPaths.p216ab100} fill="var(--logo-base)" id="Vector_7" />
          <path d={svgPaths.p1e300000} fill="var(--logo-primary)" id="Vector_8" />
          <path d={svgPaths.p61f8800} fill="var(--logo-soft)" id="Vector_9" />
          <path d={svgPaths.p32288800} fill="var(--logo-deep)" id="Vector_10" />
          <path d={svgPaths.p17c76f00} fill="var(--logo-deep)" id="Vector_11" />
          <path d={svgPaths.p18656b00} fill="var(--logo-soft)" id="Vector_12" />
          <path d={svgPaths.p2890fc00} fill="var(--logo-base)" id="Vector_13" />
          <path d={svgPaths.p2a843252} fill="var(--logo-soft)" id="Vector_14" />
          <path d={svgPaths.p31cd000} fill="var(--logo-primary)" id="Vector_15" />
          <path d={svgPaths.p22bb2480} fill="var(--logo-deep)" id="Vector_16" />
          <path d={svgPaths.p2e1b280} fill="var(--logo-base)" id="Vector_17" />
          <path d={svgPaths.p286dcc80} fill="var(--logo-soft)" id="Vector_18" />
          <path d={svgPaths.p1b062100} fill="var(--logo-base)" id="Vector_19" />
          <path d={svgPaths.pbf1f000} fill="var(--logo-primary)" id="Vector_20" />
          <path d={svgPaths.p18d8be80} fill="var(--logo-deep)" id="Vector_21" />
          <path d={svgPaths.p28658970} fill="var(--logo-soft)" id="Vector_22" />
          <path d={svgPaths.p3a879f80} fill="var(--logo-primary)" id="Vector_23" />
          <path d={svgPaths.pedcbd00} fill="var(--logo-soft)" id="Vector_24" />
          <path d={svgPaths.p1c4edc80} fill="var(--logo-primary)" id="Vector_25" />
          <path d={svgPaths.p16248a80} fill="var(--logo-soft)" id="Vector_26" />
          <path d={svgPaths.p394a6600} fill="var(--logo-soft)" id="Vector_27" />
          <path d={svgPaths.p32076f0} fill="var(--logo-primary)" id="Vector_28" />
          <path d={svgPaths.pf56b800} fill="var(--logo-primary)" id="Vector_29" />
          <path d={svgPaths.pf987d00} fill="var(--logo-soft)" id="Vector_30" />
          <path d={svgPaths.p2af9e200} fill="var(--logo-soft)" id="Vector_31" />
          <path d={svgPaths.pa2f8f80} fill="var(--logo-deep)" id="Vector_32" />
          <path d={svgPaths.p268fc780} fill="var(--logo-soft)" id="Vector_33" />
          <path d={svgPaths.p1174a500} fill="var(--logo-soft)" id="Vector_34" />
          <path d={svgPaths.pf3e52f0} fill="var(--logo-soft)" id="Vector_35" />
          <path d={svgPaths.p68de100} fill="var(--logo-deep)" id="Vector_36" />
          <path d={svgPaths.p2b9e0300} fill="var(--logo-primary)" id="Vector_37" />
          <path d={svgPaths.p2d942d00} fill="var(--logo-soft)" id="Vector_38" />
          <path d={svgPaths.p11c38380} fill="var(--logo-base)" id="Vector_39" />
          <path d={svgPaths.p8bc8300} fill="var(--logo-primary)" id="Vector_40" />
          <path d={svgPaths.p2b5708f0} fill="var(--logo-deep)" id="Vector_41" />
          <path d={svgPaths.p136ad800} fill="var(--logo-soft)" id="Vector_42" />
          <path d={svgPaths.p1e81a700} fill="var(--logo-primary)" id="Vector_43" />
          <path d={svgPaths.p1725de00} fill="var(--logo-soft)" id="Vector_44" />
          <path d={svgPaths.p12f5680} fill="var(--logo-primary)" id="Vector_45" />
          <path d={svgPaths.p3ea6df00} fill="var(--logo-soft)" id="Vector_46" />
          <path d={svgPaths.p32ea1e00} fill="var(--logo-soft)" id="Vector_47" />
          <path d={svgPaths.pd221400} fill="var(--logo-soft)" id="Vector_48" />
          <path d={svgPaths.p3f628b00} fill="var(--logo-soft)" id="Vector_49" />
          <path d={svgPaths.p259db000} fill="var(--logo-deep)" id="Vector_50" />
          <path d={svgPaths.p1e7e8000} fill="var(--logo-primary)" id="Vector_51" />
          <path d={svgPaths.p5e70900} fill="var(--logo-primary)" id="Vector_52" />
          <path d={svgPaths.p14a9e800} fill="var(--logo-base)" id="Vector_53" />
          <path d={svgPaths.p2a209b80} fill="var(--logo-soft)" id="Vector_54" />
          <path d={svgPaths.p31111600} fill="var(--logo-primary)" id="Vector_55" />
          <path d={svgPaths.pf5b3600} fill="var(--logo-primary)" id="Vector_56" />
          <path d={svgPaths.pf600400} fill="var(--logo-soft)" id="Vector_57" />
          <path d={svgPaths.p2b32c800} fill="var(--logo-primary)" id="Vector_58" />
          <path d={svgPaths.p3f7bc680} fill="var(--logo-soft)" id="Vector_59" />
          <path d={svgPaths.p2560fa00} fill="var(--logo-soft)" id="Vector_60" />
          <path d={svgPaths.p9463d40} fill="var(--logo-soft)" id="Vector_61" />
          <path d={svgPaths.p2dc33580} fill="var(--logo-soft)" id="Vector_62" />
          <path d={svgPaths.p2c39ea00} fill="var(--logo-deep)" id="Vector_63" />
          <path d={svgPaths.p2ea89480} fill="var(--logo-soft)" id="Vector_64" />
          <path d={svgPaths.pd44cf00} fill="var(--logo-deep)" id="Vector_65" />
          <path d={svgPaths.p1bf3d800} fill="var(--logo-soft)" id="Vector_66" />
          <path d={svgPaths.p5d6ee80} fill="var(--logo-soft)" id="Vector_67" />
          <path d={svgPaths.p25785a80} fill="var(--logo-deep)" id="Vector_68" />
          <path d={svgPaths.p3f7e3d00} fill="var(--logo-soft)" id="Vector_69" />
          <path d={svgPaths.p3753f0} fill="var(--logo-soft)" id="Vector_70" />
          <path d={svgPaths.p19c188f0} fill="var(--logo-soft)" id="Vector_71" />
          <path d={svgPaths.p38090880} fill="var(--logo-primary)" id="Vector_72" />
          <path d={svgPaths.p3344d00} fill="var(--logo-primary)" id="Vector_73" />
          <path d={svgPaths.p3382ca80} fill="var(--logo-soft)" id="Vector_74" />
          <path d={svgPaths.pdf3bdf0} fill="var(--logo-soft)" id="Vector_75" />
          <path d={svgPaths.p193c6780} fill="var(--logo-deep)" id="Vector_76" />
          <path d={svgPaths.p5e92180} fill="var(--logo-soft)" id="Vector_77" />
          <path d={svgPaths.p16378100} fill="var(--logo-soft)" id="Vector_78" />
          <path d={svgPaths.pd06e280} fill="var(--logo-soft)" id="Vector_79" />
          <path d={svgPaths.pf7db3b0} fill="var(--logo-deep)" id="Vector_80" />
          <path d={svgPaths.p1cc6a780} fill="var(--logo-deep)" id="Vector_81" />
          <path d={svgPaths.p3e357f80} fill="var(--logo-soft)" id="Vector_82" />
          <path d={svgPaths.p1ecb34f0} fill="var(--logo-soft)" id="Vector_83" />
          <path d={svgPaths.p166c2b00} fill="var(--logo-soft)" id="Vector_84" />
          <path d={svgPaths.p20710cf0} fill="var(--logo-soft)" id="Vector_85" />
          <path d={svgPaths.p45f0180} fill="var(--logo-soft)" id="Vector_86" />
          <path d={svgPaths.p128a3100} fill="var(--logo-soft)" id="Vector_87" />
          <path d={svgPaths.p32be8f30} fill="var(--logo-primary)" id="Vector_88" />
          <path d={svgPaths.p106c3400} fill="var(--logo-primary)" id="Vector_89" />
          <path d={svgPaths.p2036d700} fill="var(--logo-soft)" id="Vector_90" />
          <path d={svgPaths.p12b23a00} fill="var(--logo-soft)" id="Vector_91" />
          <path d={svgPaths.p2723a700} fill="var(--logo-deep)" id="Vector_92" />
          <path d={svgPaths.p40be200} fill="var(--logo-soft)" id="Vector_93" />
          <path d={svgPaths.p1a7f1bc0} fill="var(--logo-primary)" id="Vector_94" />
          <path d={svgPaths.p2e197400} fill="var(--logo-deep)" id="Vector_95" />
          <path d={svgPaths.p35bcb300} fill="var(--logo-deep)" id="Vector_96" />
          <path d={svgPaths.p15dd66c0} fill="var(--logo-deep)" id="Vector_97" />
          <path d={svgPaths.p8503200} fill="var(--logo-primary)" id="Vector_98" />
          <path d={svgPaths.pf2f380} fill="var(--logo-soft)" id="Vector_99" />
          <path d={svgPaths.p3525ef00} fill="var(--logo-soft)" id="Vector_100" />
          <path d={svgPaths.p292d3500} fill="var(--logo-deep)" id="Vector_101" />
          <path d={svgPaths.p236e2100} fill="var(--logo-soft)" id="Vector_102" />
          <path d={svgPaths.p3947e800} fill="var(--logo-deep)" id="Vector_103" />
          <path d={svgPaths.pdfe9400} fill="var(--logo-primary)" id="Vector_104" />
          <path d={svgPaths.pb81ac00} fill="var(--logo-deep)" id="Vector_105" />
          <path d={svgPaths.p28e7200} fill="var(--logo-deep)" id="Vector_106" />
          <path d={svgPaths.p2294bb00} fill="var(--logo-deep)" id="Vector_107" />
          <path d={svgPaths.p14fb4300} fill="var(--logo-deep)" id="Vector_108" />
          <path d={svgPaths.p1d895180} fill="var(--logo-deep)" id="Vector_109" />
          <path d={svgPaths.p784c200} fill="var(--logo-deep)" id="Vector_110" />
          <path d={svgPaths.p15366b00} fill="var(--logo-soft)" id="Vector_111" />
          <path d={svgPaths.p19691300} fill="var(--logo-deep)" id="Vector_112" />
          <path d={svgPaths.paf84300} fill="var(--logo-primary)" id="Vector_113" />
          <path d={svgPaths.pc4ecb80} fill="var(--logo-deep)" id="Vector_114" />
          <path d={svgPaths.p2c96eb00} fill="var(--logo-deep)" id="Vector_115" />
          <path d={svgPaths.p438c800} fill="var(--logo-primary)" id="Vector_116" />
          <path d={svgPaths.p7af5c80} fill="var(--logo-deep)" id="Vector_117" />
          <path d={svgPaths.p34823780} fill="var(--logo-primary)" id="Vector_118" />
          <path d={svgPaths.p22311400} fill="var(--logo-deep)" id="Vector_119" />
          <path d={svgPaths.p309da500} fill="var(--logo-soft)" id="Vector_120" />
          <path d={svgPaths.p3c646e00} fill="var(--logo-deep)" id="Vector_121" />
          <path d={svgPaths.p38ed8580} fill="var(--logo-deep)" id="Vector_122" />
          <path d={svgPaths.p319155f0} fill="var(--logo-primary)" id="Vector_123" />
          <path d={svgPaths.p350fc180} fill="var(--logo-deep)" id="Vector_124" />
          <path d={svgPaths.p2c3a4380} fill="var(--logo-primary)" id="Vector_125" />
          <path d={svgPaths.p4c9d700} fill="var(--logo-deep)" id="Vector_126" />
          <path d={svgPaths.p3d54500} fill="var(--logo-base)" id="Vector_127" />
          <path d={svgPaths.pd4af780} fill="var(--logo-soft)" id="Vector_128" />
          <path d={svgPaths.p15d1a900} fill="var(--logo-deep)" id="Vector_129" />
          <path d={svgPaths.p1491d500} fill="var(--logo-primary)" id="Vector_130" />
          <path d={svgPaths.p19d01d00} fill="var(--logo-soft)" id="Vector_131" />
          <path d={svgPaths.p3cad2000} fill="var(--logo-deep)" id="Vector_132" />
          <path d={svgPaths.p21135400} fill="var(--logo-deep)" id="Vector_133" />
          <path d={svgPaths.paa4b400} fill="var(--logo-deep)" id="Vector_134" />
          <path d={svgPaths.p123aa600} fill="var(--logo-deep)" id="Vector_135" />
          <path d={svgPaths.p2944a800} fill="var(--logo-deep)" id="Vector_136" />
          <path d={svgPaths.p2f4e1300} fill="var(--logo-primary)" id="Vector_137" />
          <path d={svgPaths.p10ad0600} fill="var(--logo-deep)" id="Vector_138" />
          <path d={svgPaths.p14d41380} fill="var(--logo-soft)" id="Vector_139" />
          <path d={svgPaths.p36d55800} fill="var(--logo-soft)" id="Vector_140" />
          <path d={svgPaths.p13b85c00} fill="var(--logo-deep)" id="Vector_141" />
          <path d={svgPaths.p352b7200} fill="var(--logo-base)" id="Vector_142" />
          <path d={svgPaths.p26497000} fill="var(--logo-soft)" id="Vector_143" />
          <path d={svgPaths.p3f9b4c00} fill="var(--logo-soft)" id="Vector_144" />
          <path d={svgPaths.p319f5500} fill="var(--logo-soft)" id="Vector_145" />
          <path d={svgPaths.p323ce100} fill="var(--logo-soft)" id="Vector_146" />
          <path d={svgPaths.p7eec600} fill="var(--logo-primary)" id="Vector_147" />
          <path d={svgPaths.p3d765f00} fill="var(--logo-deep)" id="Vector_148" />
          <path d={svgPaths.p1de2d800} fill="var(--logo-primary)" id="Vector_149" />
          <path d={svgPaths.p11ff7a00} fill="var(--logo-deep)" id="Vector_150" />
          <path d={svgPaths.p2ce2500} fill="var(--logo-soft)" id="Vector_151" />
          <path d={svgPaths.p1c9b1a00} fill="var(--logo-soft)" id="Vector_152" />
          <path d={svgPaths.p3ded3980} fill="var(--logo-deep)" id="Vector_153" />
          <path d={svgPaths.p199f9180} fill="var(--logo-primary)" id="Vector_154" />
          <path d={svgPaths.p15d5e800} fill="var(--logo-primary)" id="Vector_155" />
          <path d={svgPaths.p21133300} fill="var(--logo-deep)" id="Vector_156" />
          <path d={svgPaths.p21063f72} fill="var(--logo-soft)" id="Vector_157" />
          <path d={svgPaths.p2002bf80} fill="var(--logo-primary)" id="Vector_158" />
          <path d={svgPaths.p2128b600} fill="var(--logo-soft)" id="Vector_159" />
          <path d={svgPaths.p317b6b00} fill="var(--logo-base)" id="Vector_160" />
          <path d={svgPaths.pe4bec00} fill="var(--logo-deep)" id="Vector_161" />
          <path d={svgPaths.p5c6500} fill="var(--logo-deep)" id="Vector_162" />
          <path d={svgPaths.p38398b40} fill="var(--logo-deep)" id="Vector_163" />
          <path d={svgPaths.p27007780} fill="var(--logo-deep)" id="Vector_164" />
          <path d={svgPaths.p9ca4500} fill="var(--logo-primary)" id="Vector_165" />
          <path d={svgPaths.p2d460700} fill="var(--logo-soft)" id="Vector_166" />
          <path d={svgPaths.p43ca200} fill="var(--logo-deep)" id="Vector_167" />
          <path d={svgPaths.pb79e300} fill="var(--logo-deep)" id="Vector_168" />
          <path d={svgPaths.p1e814500} fill="var(--logo-primary)" id="Vector_169" />
          <path d={svgPaths.p1c706400} fill="var(--logo-deep)" id="Vector_170" />
          <path d={svgPaths.p1be8f400} fill="var(--logo-soft)" id="Vector_171" />
          <path d={svgPaths.p1b4eb700} fill="var(--logo-soft)" id="Vector_172" />
          <path d={svgPaths.pe3a6b80} fill="var(--logo-soft)" id="Vector_173" />
          <path d={svgPaths.pbdea3a0} fill="var(--logo-soft)" id="Vector_174" />
          <path d={svgPaths.pbc72480} fill="var(--logo-soft)" id="Vector_175" />
          <path d={svgPaths.p2ba5fe30} fill="var(--logo-deep)" id="Vector_176" />
          <path d={svgPaths.p1f455500} fill="var(--logo-deep)" id="Vector_177" />
          <path d={svgPaths.p3db7dd20} fill="var(--logo-deep)" id="Vector_178" />
          <path d={svgPaths.p3ae798c0} fill="var(--logo-deep)" id="Vector_179" />
          <path d={svgPaths.p2e1b5300} fill="var(--logo-deep)" id="Vector_180" />
          <path d={svgPaths.p1e7dba40} fill="var(--logo-deep)" id="Vector_181" />
          <path d={svgPaths.pe23cc70} fill="var(--logo-deep)" id="Vector_182" />
          <path d={svgPaths.p1eacbf00} fill="var(--logo-deep)" id="Vector_183" />
          <path d={svgPaths.p3c77380} fill="var(--logo-deep)" id="Vector_184" />
          <path d={svgPaths.p6ddd71} fill="var(--logo-deep)" id="Vector_185" />
          <path d={svgPaths.p227db000} fill="var(--logo-base)" id="Vector_186" />
          <path d={svgPaths.p2eb10400} fill="var(--logo-deep)" id="Vector_187" />
          <path d={svgPaths.p589f9f0} fill="var(--logo-deep)" id="Vector_188" />
          <path d={svgPaths.p9115200} fill="var(--logo-deep)" id="Vector_189" />
          <path d={svgPaths.pc775500} fill="var(--logo-deep)" id="Vector_190" />
          <path d={svgPaths.p2ecf4c00} fill="var(--logo-deep)" id="Vector_191" />
          <path d={svgPaths.p3a5c700} fill="var(--logo-deep)" id="Vector_192" />
          <path d={svgPaths.p42c2880} fill="var(--logo-base)" id="Vector_193" />
          <path d={svgPaths.p38b2d500} fill="var(--logo-deep)" id="Vector_194" />
          <path d={svgPaths.p187f6b20} fill="var(--logo-deep)" id="Vector_195" />
          <path d={svgPaths.p2e9db800} fill="var(--logo-deep)" id="Vector_196" />
          <path d={svgPaths.p343b4b00} fill="var(--logo-deep)" id="Vector_197" />
          <path d={svgPaths.p5b3a800} fill="var(--logo-deep)" id="Vector_198" />
          <path d={svgPaths.p370d5d00} fill="var(--logo-deep)" id="Vector_199" />
          <path d={svgPaths.p19c39100} fill="var(--logo-deep)" id="Vector_200" />
          <path d={svgPaths.p36623780} fill="var(--logo-deep)" id="Vector_201" />
          <path d={svgPaths.p13b83600} fill="var(--logo-deep)" id="Vector_202" />
          <path d={svgPaths.p3534200} fill="var(--logo-deep)" id="Vector_203" />
          <path d={svgPaths.pdfd0f80} fill="var(--logo-deep)" id="Vector_204" />
          <path d={svgPaths.p8775900} fill="var(--logo-deep)" id="Vector_205" />
          <path d={svgPaths.p19f6500} fill="var(--logo-deep)" id="Vector_206" />
          <path d={svgPaths.pdb50d00} fill="var(--logo-deep)" id="Vector_207" />
          <path d={svgPaths.p38f10431} fill="var(--logo-deep)" id="Vector_208" />
          <path d={svgPaths.p1bba7f00} fill="var(--logo-primary)" id="Vector_209" />
          <path d={svgPaths.p3b646380} fill="var(--logo-primary)" id="Vector_210" />
          <path d={svgPaths.p3798a980} fill="var(--logo-deep)" id="Vector_211" />
          <path d={svgPaths.p22f48d00} fill="var(--logo-primary)" id="Vector_212" />
          <path d={svgPaths.p77a1c00} fill="var(--logo-primary)" id="Vector_213" />
          <path d={svgPaths.p3603a080} fill="var(--logo-primary)" id="Vector_214" />
          <path d={svgPaths.p1b9dd5e0} fill="var(--logo-primary)" id="Vector_215" />
          <path d={svgPaths.p2c621b80} fill="var(--logo-soft)" id="Vector_216" />
          <path d={svgPaths.p1e462680} fill="var(--logo-primary)" id="Vector_217" />
          <path d={svgPaths.p14ae9a00} fill="var(--logo-primary)" id="Vector_218" />
          <path d={svgPaths.p39c00b80} fill="var(--logo-primary)" id="Vector_219" />
          <path d={svgPaths.pc45cf00} fill="var(--logo-deep)" id="Vector_220" />
          <path d={svgPaths.p340cb00} fill="var(--logo-deep)" id="Vector_221" />
          <path d={svgPaths.p10ce5b80} fill="var(--logo-deep)" id="Vector_222" />
          <path d={svgPaths.p3c8f9900} fill="var(--logo-soft)" id="Vector_223" />
          <path d={svgPaths.p170a9e80} fill="var(--logo-deep)" id="Vector_224" />
          <path d={svgPaths.p2cad6b00} fill="var(--logo-soft)" id="Vector_225" />
          <path d={svgPaths.p136eb980} fill="var(--logo-soft)" id="Vector_226" />
          <path d={svgPaths.p257039c0} fill="var(--logo-soft)" id="Vector_227" />
          <path d={svgPaths.p3d489300} fill="var(--logo-soft)" id="Vector_228" />
          <path d={svgPaths.p3a148200} fill="var(--logo-soft)" id="Vector_229" />
          <path d={svgPaths.p1ff13900} fill="var(--logo-primary)" id="Vector_230" />
          <path d={svgPaths.pcaffd00} fill="var(--logo-deep)" id="Vector_231" />
          <path d={svgPaths.p2c125c80} fill="var(--logo-primary)" id="Vector_232" />
          <path d={svgPaths.p3fcd3280} fill="var(--logo-deep)" id="Vector_233" />
          <path d={svgPaths.p261daa00} fill="var(--logo-deep)" id="Vector_234" />
          <path d={svgPaths.p2d90d480} fill="var(--logo-primary)" id="Vector_235" />
          <path d={svgPaths.p171b1f80} fill="var(--logo-primary)" id="Vector_236" />
          <path d={svgPaths.p1dca3f80} fill="var(--logo-primary)" id="Vector_237" />
          <path d={svgPaths.p2ae71e70} fill="var(--logo-primary)" id="Vector_238" />
        </g>
        <defs>
          <clipPath id="clip0_33_1121">
            <rect fill="white" height="1914.2" width="1840.38" />
          </clipPath>
        </defs>
      </svg>
    </div>
  );
}